export type Material = {
  slug: string;
  title: string;
  category: string;
  theme: string;
  description: string;
  highlights?: string[];
  cover?: string;
};

export const materiais: Material[] = [
  {
    slug: "diminua-o-turnover",
    theme: "Cultura & Engajamento",
    title: "Diminua o TurnOver",
    category: "E-book",
    description: "Descubra estratégias práticas para reduzir a rotatividade e fortalecer o engajamento dos colaboradores e criar um time de alta retenção.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/23-r9fdw9umpxzbjfkk8vent7rh190f18uu8locug9b1s.png",
  },
  {
    slug: "100-perguntas-para-1a1",
    theme: "Liderança & Feedback",
    title: "100 Perguntas para 1A1",
    category: "E-book",
    description: "Inspire conversas mais produtivas e humanas entre líderes e equipes com este guia completo de perguntas.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/21-r9fdwfhnuy71h3cdbxuf86c8lk8mbfh89dl9q40y0g.png",
  },
  {
    slug: "cultura-de-feedback",
    theme: "Liderança & Feedback",
    title: "Cultura de Feedback",
    category: "E-book",
    description: "Aprenda como criar um ambiente onde o feedback é contínuo, respeitoso e voltado ao crescimento profissional.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/20-r9fdwbqb3m1w6nhtxw7wy7ae80r5gn2awuzbt06ipc.png",
  },
  {
    slug: "guia-para-feedback-aplicado-a-avaliacao-de-desempenho",
    theme: "Liderança & Feedback",
    title: "Guia para Feedback Aplicado a Avaliação de Desempenho",
    category: "E-book",
    description: "Um passo a passo para aplicar feedbacks objetivos, assertivos e alinhados aos resultados organizacionais.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/19-r9fdvut7oleqdo6eoowmpbk3j32jm374uj8l60vltc.png",
  },
  {
    slug: "como-construir-um-ambiente-de-trabalho-inclusivo",
    theme: "Diversidade & Inclusão",
    title: "Como Construir um Ambiente de Trabalho Inclusivo",
    category: "E-book",
    description: "Práticas eficazes para promover a inclusão de pessoas LGBTQIA+ e fortalecer a cultura de respeito e diversidade.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/18-r9fdw7145fvgklonpc6s3qh393ebe5jn87pwemdhkg.png",
  },
  {
    slug: "geracoes-e-sua-relacao-no-ambiente-de-trabalho",
    theme: "Diversidade & Inclusão",
    title: "Gerações e Sua Relação no Ambiente de Trabalho nos tempos atuais",
    category: "E-book",
    description: "Entenda como integrar diferentes gerações e promover colaboração e harmonia entre perfis diversos nas equipes.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/22-r9fdwib6fgawfx89vh2axnmmdpupyisf9rjq5xwrhs.png",
  },
  {
    slug: "apostas-ansiedade-e-absenteismo",
    theme: "Saúde Mental",
    title: "Apostas, Ansiedade e Absenteísmo",
    category: "E-book",
    description: "Um alerta sobre os impactos silenciosos das apostas no ambiente de trabalho e como o RH pode agir com empatia.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/16-r9fdw39re3qba5u4bak9trf8vjwujd4pvp3yhij29c.png",
  },
  {
    slug: "a-nova-nr01-e-a-importancia-do-rh",
    theme: "RH Estratégico",
    title: "A Nova NR01 e a Importância do RH",
    category: "E-book",
    description: "Saiba o que mudou com a nova NR01 e como o RH pode liderar ações preventivas para a saúde mental e segurança no trabalho.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/14-r9fdvxmq93ilci2b884iesuhb8on96ibux71lurfao.png",
  },
  {
    slug: "rh-eficiente-com-o-bpo",
    theme: "RH Estratégico",
    title: "RH Eficiente com o BPO",
    category: "E-book",
    description: "Entenda como o BPO de RH pode otimizar processos, reduzir custos e tornar sua gestão de pessoas mais estratégica em apenas cinco passos práticos.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/17-r9fdw55frrsvxdre0bdiyqy62bnkyrc6jyexg2g9ww.png",
  },
  {
    slug: "res-como-escolher-os-candidatos-para-sua-cultura",
    theme: "Recrutamento & Seleção",
    title: "R&S: Como escolher os candidatos para sua Cultura Organizacional",
    category: "E-book",
    description: "Descubra como selecionar candidatos que realmente se conectam com os valores da sua empresa.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/26-r9vb9hfo208q7n272ndhpz7it540hg15t3xtzpbvao.png",
  },
  {
    slug: "diversidade-equidade-e-inclusao-no-ambiente-corporativo",
    theme: "Diversidade & Inclusão",
    title: "Diversidade, equidade e inclusão no ambiente corporativo",
    category: "E-book",
    description: "Saiba como tornar sua empresa mais inclusiva com práticas eficazes para promover o respeito à diversidade.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/27-r9vb9k96micl6gy3m6ldfghwlaq44jccthwafj7os0.png",
  },
  {
    slug: "como-acertar-no-res-e-evitar-erros-caros",
    theme: "Recrutamento & Seleção",
    title: "Como acertar no R&S e evitar erros caros?",
    category: "E-book",
    description: "Aprenda a evitar contratações equivocadas e a formar equipes mais integradas e produtivas.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/25-r9vb9em5hi4v8t6aj45m0hx50zhwucpyspzdjvg1tc.png",
  },
  {
    slug: "como-aplicar-a-saude-mental-como-beneficio-estrategico",
    theme: "Saúde Mental",
    title: "Como aplicar a saúde mental como benefício estratégico para melhorar o engajamento e a produtividade",
    category: "E-book",
    description: "Descubra como transformar a saúde mental em um benefício estratégico dentro da sua empresa.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-26-ra902ra0csphx6vdhwue1j27bqmseonoo9cvmq604w.png",
  },
  {
    slug: "burnout-como-reconhecer-os-sinais-na-equipe-e",
    theme: "Saúde Mental",
    title: "Burnout: Como reconhecer os sinais na equipe e agir para prevenir",
    category: "E-book",
    description: "Aprenda a identificar os sinais de burnout e outros sintomas de desgaste emocional na sua equipe antes que se tornem problemas graves.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-27-ra9046z4soo9nqsa416vco0jzxjz61cx7d8l0y1cmo.png",
  },
  {
    slug: "como-criar-uma-cultura-de-aprendizagem-continua",
    theme: "Cultura & Engajamento",
    title: "Como Criar uma Cultura de Aprendizagem Contínua",
    category: "E-book",
    description: "Dicas práticas para implantar uma cultura de desenvolvimento constante, com foco em inovação e crescimento.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/15-r9fdw0g8tlmgbby7rrce4a4v3eaqw9tivb5i1on8s0.png",
  },
  {
    slug: "setembro-amarelo-o-papel-das-empresas-na-prevencao",
    theme: "Campanhas & Datas",
    title: "Setembro Amarelo: O papel das empresas na prevenção do suicídio",
    category: "E-book",
    description: "Saiba mais sobre como sua empresa pode atuar na prevenção do suicídio e na promoção da saúde mental, fortalecendo pessoas e organizações.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-37-e1756409955411-raxqvabo423un7jkt7kqwnbn46xnxlhu0qphhju7g0.png",
  },
  {
    slug: "tradurh-traduzindo-o-rh-para-voce",
    theme: "RH Estratégico",
    title: "TraduRH: Traduzindo o Rh para você",
    category: "E-book",
    description: "Um guia prático e atualizado para profissionais de Recursos Humanos, gestores e empresários que desejam compreender os principais termos da área.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-51-rch1k3puwbu67cedm7z9ts48rm6cn4ukonf03zp8vk.png",
  },
  {
    slug: "gestao-geracional",
    theme: "Diversidade & Inclusão",
    title: "Gestão Geracional",
    category: "E-book",
    description: "Como transformar diferenças de idade em vantagem competitiva? Você vai descobrir estratégias práticas para gerenciar equipes multigeracionais, aproveitando o melhor de cada geração.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-52-rch1zvgdk9fczthpj1dxnsunkcg1sbgg6pg9z4bghc.png",
  },
  {
    slug: "cartilha-outubro-rosa",
    theme: "Campanhas & Datas",
    title: "Cartilha Outubro Rosa",
    category: "E-book",
    description: "Saiba mais dos principais dados, orientações de autocuidado, mitos e verdades, e também inspirações para engajamento coletivo. Um material simples, mas poderoso, para lembrar que cuidar da saúde deve vir sempre em primeiro lugar.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-1-rdao0gg8ak2qhpd38izz8lr7lr5gu5tyh5p2auz4mo.png",
  },
  {
    slug: "endomarketing-e-cultura",
    theme: "Cultura & Engajamento",
    title: "Endomarketing & Cultura",
    category: "E-book",
    description: "Descubra como alinhar comunicação interna e cultura organizacional para gerar engajamento, confiança e bem-estar, com insights e exemplos aplicáveis.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-rdankedhjg3e5ios034f55mq9saqcb319ohg5os8xc.png",
  },
  {
    slug: "cartilha-novembro-azul",
    theme: "Campanhas & Datas",
    title: "Cartilha Novembro Azul",
    category: "E-book",
    description: "Este material reúne os principais dados sobre a saúde do homem, orientações práticas de autocuidado, mitos e verdades que precisam ser desmistificados e ideias inspiradoras para mobilizar o time em torno dessa causa.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-3-rdz0rhugp9hvl0ae9bp37a4quiy8wvwozp1d4q5640.png",
  },
  {
    slug: "celebracoes-que-conectam",
    theme: "Cultura & Engajamento",
    title: "Celebrações que Conectam",
    category: "E-book",
    description: "Este e-book reúne orientações práticas e insights estratégicos para ajudar empresários e profissionais de RH a planejarem confraternizações de fim de ano.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-12-rfmgjuue5azp34hidhivgxlqyi8yc21iahdyfzhs8g.png",
  },
  {
    slug: "cartilha-janeiro-branco",
    theme: "Campanhas & Datas",
    title: "Cartilha Janeiro Branco",
    category: "E-book",
    description: "Nesta cartilha, você encontrará temas como: autocuidado, identificação de sinais de alerta, manejo do estresse, equilíbrio entre vida pessoal e profissional e dicas para cultivar relações mais saudáveis.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-15-rfynvttjujv468wl7iznlbt8etc601cp49valiztww.png",
  },
  {
    slug: "equidade-de-genero-no-mercado-de-trabalho",
    theme: "Diversidade & Inclusão",
    title: "Equidade de Gênero no Mercado de Trabalho",
    category: "E-book",
    description: "Aqui você encontrará uma abordagem clara e envolvente sobre os desafios enfrentados pelas mulheres no ambiente profissional, além de caminhos possíveis para promover mudanças.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-18-rkqxtwm74prodmnrrqw0wegmf5jl2t31kk0ue884ds.png",
  },
  {
    slug: "comunicacao-assertiva-pela-lideranca",
    theme: "Liderança & Feedback",
    title: "Comunicação Assertiva pela Liderança",
    category: "E-book",
    description: "Neste e-book, você vai descobrir como desenvolver uma comunicação mais clara, assertiva e estratégica no dia a dia, evitando conflitos, fortalecendo relações e conduzindo sua equipe com mais confiança.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-21-rmfkyivqzl4zlyhw2u6wittcdcj4eybydwfmle604w.png",
  },
  {
    slug: "a-revolucao-50-no-mercado",
    theme: "Diversidade & Inclusão",
    title: "A revolução 50+ no Mercado",
    category: "E-book",
    description: "A experiência nunca foi tão estratégica. Descubra por que os profissionais 50+ estão redefinindo o mercado de trabalho e como sua empresa pode transformar diversidade geracional em inovação, produtividade e vantagem competitiva.",
    cover: "https://pensecom.com.br/site/wp-content/uploads/elementor/thumbs/MKT-I-Imagens-Site-24-rrf01u4wblhzsflnw1r9rdck8n05srn7x8pjh3lovk.png",
  },
];

export const findMaterial = (slug: string) =>
  materiais.find((m) => m.slug === slug);

export const temas = Array.from(new Set(materiais.map((m) => m.theme))).sort();
